import Head from "next/head";

import styles from "../../../styles/Home.module.css";

import { useRouter } from "next/router";
import Link from "next/link";

export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Post Klasörü İndex Sayfamız</h1>

        <p className={styles.description}>
          Şuan Aktif olan Path :
          <code className={styles.code}>localost:3000{router.asPath}</code>
        </p>

        <div className={styles.grid}>
        <ul>
      <li>
        <Link href="/">
          <a>Ana Sayfa</a>
        </Link>
      </li>
      <li>
        <Link href="/post/first">
          <a>İlk Post</a>
        </Link>
      </li>
      <li>
        <Link href="/post/second">
          <a>İkinci Post</a>
        </Link>
      </li>
    </ul>
        </div>
      </main>


    </div>
  );
}



