import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import { useRouter } from 'next/router'
import Link from 'next/link'
export default function Home() {
  const router = useRouter();
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Pictures Ana Sayfamız</h1>
       
        <p className={styles.description}>Şuan Aktif olan Path : <code className={styles.code}>localost:3000{router.asPath}</code></p>

        <Link href="/">Geri Dön</Link>
        </main>
       <img src='https://ms314006.github.io/static/b7a8f321b0bbc07ca9b9d22a7a505ed5/97b31/React.jpg' width={820} height={520}></img>
     
       <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Nextjs-logo.svg/1200px-Nextjs-logo.svg.png' width={820} height={520}></img>
      

    </div>
  )
}
