import { useRouter } from 'next/router'
import Link from 'next/link'
import styles from "../../../styles/Home.module.css";
import Head from "next/head";
const Post = () => {
  const router = useRouter()
  const { id } = router.query

  return (
    <>
      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{id} id bilgisine  sahip post</h1>

        <p className={styles.description}>
          Şuan Aktif olan Path :
          <code className={styles.code}>localost:3000{router.asPath}</code>
        </p>

        <div className={styles.grid}>
        <ul>
        <li>
          <Link href="/post/[id]/[comment]" as={`/post/${id}/first-comment`}>
            <a>İlk Yorum</a>
          </Link>
        </li>
        <li>
          <Link href="/post/[id]/[comment]" as={`/post/${id}/second-comment`}>
            <a>İkinci yorum</a>
          </Link>
        </li>
    </ul>
        </div>
      </main>


    </div>


    </>
  )
}

export default Post
